### ISSUE TITLE
Sources qbusmqtt

### ISSUE THREAD

**Issue by jschaeke** [QbusKoen/qbusMqtt#1]
I was wondering what this qbusmqtt supported. I don't own a qbus installation myself, so can't test but I have a friend who I help out with his qbus... he now asks me to help him getting it on his home assistant. Will you publish also the sources and or documentation with features?

**Comment by Qbus-Koen** [comment]
Hi @jschaeke 
Sorry for late reply.
The source of this project is not open-source.
With this project we provide a sort of gateway between the CTD and MQTT, because our current controller does not support MQTT.
The protocol however is set up in a way that our new controller will use the same protocol.

For the moment we do not support HA, but you can use openHAB. From there you can send / receive data from / to HA.

We do have plans to support HA in the near future...

**Comment by jschaeke** [comment]
Good to hear home assistant is on the radar. Hopefully its integration will be worked out soon and becomes as easy as for example Velbus which I personally own (2 clicks installation and my Velbus devices appeared in HA).
For my friend situation we sticked to the little qbusmqtt script I made earlier to get it in home assistant. It can run in a container on the home assistant installation itself on the same raspberry so the openhab workaround is not necessary.
